### ISSUE TITLE
Detect if a Wayland server is present

### ISSUE THREAD

**Issue by benmoran56** [sde1000/python-wayland#2]
Currently, the test.py script fails with a FileNotFound exception if you are not running under a Wayland session. It would be much nicer if it could detect if a Wayland server is present, and fail gracefully with an informative message if not. The current traceback is: 

```
Traceback (most recent call last):
  File "test.py", line 434, in <module>
    conn = WaylandConnection()
  File "test.py", line 313, in __init__
    self.display = Display()
  File "/home/ben/Desktop/python-wayland/wayland/client.py", line 63, in __init__
    self._f.connect(path)
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by sde1000** [comment]
I could catch FileNotFoundError in the test script and print an additional message, I suppose.  I don't really want to catch and reraise the exception in Display() at this point because doing so may hide other problems that might come up.

(Very experimental software at the moment, I don't want to commit to an API with its own set of exceptions just yet.)

**Comment by benmoran56** [comment]
Thanks for the reply. That does make sense.
